import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import Sidebar from '@/components/sidebar/sidebar';
import Header from '@/components/header/header';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`flex ${inter.className}`}>
        <Sidebar />
        <main className="w-full min-h-screen">
          <Header />
          <div className="p-8">
            {children}

          </div>
        </main>
      </body>
    </html>
  );
}
